/**
 * Street2Ivy — Custom Node.js server for Heroku deployment
 *
 * In production (with output: 'standalone'), uses the standalone server.
 * In development, wraps Next.js directly.
 */

const hostname = '0.0.0.0';
const port = parseInt(process.env.PORT || '3000', 10);

if (process.env.NODE_ENV === 'production') {
  // Production: use the standalone server generated by Next.js build
  process.env.HOSTNAME = hostname;
  process.env.PORT = String(port);
  require('./.next/standalone/server.js');
} else {
  // Development: wrap Next.js directly
  const { createServer } = require('http');
  const { parse } = require('url');
  const next = require('next');

  const app = next({ dev: true, hostname, port });
  const handle = app.getRequestHandler();

  app.prepare().then(() => {
    createServer(async (req, res) => {
      try {
        const parsedUrl = parse(req.url, true);
        await handle(req, res, parsedUrl);
      } catch (err) {
        console.error('Error occurred handling', req.url, err);
        res.statusCode = 500;
        res.end('Internal Server Error');
      }
    })
      .once('error', (err) => {
        console.error(err);
        process.exit(1);
      })
      .listen(port, hostname, () => {
        console.log(`> Street2Ivy ready on http://${hostname}:${port}`);
      });
  });
}
