'use client';

/**
 * AI Disclaimer / Bias Warning Component
 *
 * Displays a standardized AI limitation and bias warning.
 * Used on all pages that display AI-generated analysis or recommendations.
 *
 * Variants:
 *   - "banner" (default): Full-width info banner with icon
 *   - "inline": Compact inline text suitable for card footers
 */

import { AlertTriangle, Info } from 'lucide-react';

interface AiDisclaimerProps {
  variant?: 'banner' | 'inline';
  className?: string;
}

const DISCLAIMER_TEXT =
  'This analysis is generated by AI based solely on submitted profile information and stated job requirements. AI can reflect biases present in data and language. Use this as one input among many — not as a sole basis for decisions.';

const LIMITATION_TEXT =
  'AI features analyze only facts explicitly provided by candidates and stated project requirements. No inferences are made based on names, demographics, or any information not directly submitted.';

export function AiDisclaimer({ variant = 'banner', className = '' }: AiDisclaimerProps) {
  if (variant === 'inline') {
    return (
      <p className={`text-xs text-slate-400 dark:text-slate-500 italic ${className}`}>
        <Info className="inline h-3 w-3 mr-1 -mt-0.5" />
        {DISCLAIMER_TEXT}
      </p>
    );
  }

  return (
    <div
      className={`rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/30 p-4 ${className}`}
    >
      <div className="flex gap-3">
        <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1.5">
          <p className="text-sm font-medium text-amber-800 dark:text-amber-300">
            AI Limitations & Bias Warning
          </p>
          <p className="text-xs text-amber-700 dark:text-amber-400">
            {LIMITATION_TEXT}
          </p>
          <p className="text-xs text-amber-600 dark:text-amber-500">
            {DISCLAIMER_TEXT}
          </p>
        </div>
      </div>
    </div>
  );
}
