// NOTE: this server is purely a dev-mode server. In production, the
// server/index.js server also serves the API routes.
// Guard: Prevent accidental use of this dev server in production.
if (process.env.NODE_ENV === 'production') {
  console.error('ERROR: server/apiServer.js is a development-only server. Use server/index.js in production.');
  process.exit(1);
}

// Configure process.env with .env.* files
require('./env').configureEnv();

const express = require('express');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const apiRouter = require('./apiRouter');
const wellKnownRouter = require('./wellKnownRouter');
const webmanifestResourceRoute = require('./resources/webmanifest');
const robotsTxtRoute = require('./resources/robotsTxt');
const sitemapResourceRoute = require('./resources/sitemap');

const radix = 10;
const PORT = parseInt(process.env.REACT_APP_DEV_API_SERVER_PORT, radix);
const app = express();

// NOTE: CORS is only needed in this dev API server because it's
// running in a different port than the main app.
const allowedOrigin = process.env.REACT_APP_MARKETPLACE_ROOT_URL;
if (!allowedOrigin) {
  console.warn('WARNING: REACT_APP_MARKETPLACE_ROOT_URL is not set. CORS origin will be undefined.');
}
app.use(
  cors({
    origin: allowedOrigin,
    credentials: true,
  })
);
app.use(cookieParser());

// Serve uploaded files in development mode
// This makes /static/uploads/... work on the API server
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) {
  fs.mkdirSync(uploadsDir, { recursive: true });
}
app.use('/static/uploads', express.static(uploadsDir));

app.use('/.well-known', wellKnownRouter);
app.use('/api', apiRouter);

// Generate web app manifest
// When developing with "yarn run dev",
// you can reach the manifest from http://localhost:3500/site.webmanifest
// The corresponding <link> element is set in src/components/Page/Page.js
app.get('/site.webmanifest', webmanifestResourceRoute);

// robots.txt and sitemap-* fetches should return similarly compressed data as server/index.js
app.use(compression());

// robots.txt is generated by resources/robotsTxt.js
// It creates the sitemap URL with the correct marketplace URL
app.get('/robots.txt', robotsTxtRoute);

// Handle different sitemap-* resources. E.g. /sitemap-index.xml
app.get('/sitemap-:resource', sitemapResourceRoute);

app.listen(PORT, () => {
  console.log(`API server listening on ${PORT}`);
});
